# Python for travis: see documentation at https://docs.travis-ci.com/user/languages/python/

language: python
python:
  - "3.6"
  - "3.7"

# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install -U Cython
  - pip install -r requirements.txt
  - pip install -U tox-travis

# Command to run tests, e.g. python setup.py test
script:
  - tox