# Python for travis: see documentation at https://docs.travis-ci.com/user/languages/python/

language: python
python:
  - "3.6"
  - "3.7"
install:
  - pip install -r requirements.txt
script:
  - pytest