# Config file for continuous integration at travis-ci.org
language: python

jobs:
  include:
    - os: linux
      language: python
      dist: xenial # Because python3.7
      python: "3.7"
      services:
        - docker # Needed for cibuildwheel

env:
  global:
    - TWINE_USERNAME=__token__ # Use API token to upload on Pypi
    - secure: O8Fi4z3ekpFq98pL27r2F9MZRaB+in+s4y/JaRjYdD6va5dB4hca0RXQpbgdltKXPN9unTV8ilsdDz8UQwVFHuxhN4oEruEU4QA3H+leaj1e7cTHbMWAGanwstmYgQPwufzgh3vz+wMjlUj5uAlDRC/2Dtk3IJ7xWGj4U+iscsudrverij3OcdqbnTvXPieI54EmbGgpWRB8nS3NRdPklohDWoM6k5RzyzpjQP55v1svVxo59Gsx3fbV1nEPZkIoCtt4gYy7q79QsqFyOoEN6v7SLW/8H5ESUrXWNZjsgmD0ZESNCpYGcJpp6b3UGJ+ZvmzmDNO+C1628hibfpD6slRiS6PByWYQPLQONfcOeSnwcicgMRTdySrDc37f3myFP0EwarU9tIgRhmdy+cNJ2K8YU90b+KfmsfYwRAeaq/d1qjLXsnmdd3uDd7U2qCsw0fGlY2glIRKdr+by/nVmK9DBSTnGKb+XcHx8h4A35kYxO/RO1/0I0wZKz7xIgZxu5dfuMoMnssAtJfqKQo2eRDKteaBqmtPqiye93LERPI2GcbWlh/yh/kjz2W7AefrtJ1a5N12YgJ1B86rhg4+PJsLoHrAGeKXXbZ2tyIgUOF1O2VMWDAIasxQeVIMYssIBc+jpPfZuAvkxbGF6yM0dGAsF7hGwZrVSx5FfHBIMr1w=
    - CIBW_SKIP="cp27-* cp33-* cp34-* cp35-*" # Skip these python versions
    - CIBW_TEST_COMMAND="python -m unittest discover -f -s {project}/FDApy/tests" # Test the created wheels
    - CIBW_BEFORE_BUILD="bash scripts/prepare_for_build.sh"
    - CC="gcc" # If Travis does not find a C compiler
    - PYTHON=python3
    - PIP=pip3


# Command to install dependencies before the installation of the package
before_install:
- sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
- sudo apt-get -q update
- sudo apt-get -y install gcc-4.8

# Command to install dependencies, e.g. pip install -r requirements.txt
install:
- $PIP install -r requirements.txt
- $PIP install -U tox-travis
- if [ "${TRAVIS_OS_NAME:-}" == "osx" ]; then
    brew update;
    brew upgrade python;
  fi
- $PIP install -e .[tests]
- $PYTHON -m unittest discover -v -f -s ./FDApy/tests
- tox
- find . -type f -iname '*.so' -print -delete

# Command to run test, e.g. python setup.py test
script:
  - $PYTHON -m pip install cibuildwheel==1.4.2
  - $PYTHON -m cibuildwheel --output-dir wheelhouse
  - ls wheelhouse

# Command for package deployment
# python setup.py bdist_wheel --plat-name manylinux1_x86_64
deploy:
  skip_cleanup: true
  provider: script
  script: $PIP install twine && $PYTHON -m twine upload --verbose --skip-existing wheelhouse/*
  on:
    branch: master
    tags: true
