# Python for travis: see documentation at https://docs.travis-ci.com/user/languages/python/

language: python
python:
  - "3.7"

# Before the installation
before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get -q update
  - sudo apt-get -y install gcc-4.8
  - sudo apt-get -y install python3.7-gdbm

# Command to install dependencies, e.g. pip install -r requirements.txt 
install:
  - pip install -r requirements.txt
  - pip install -U tox-travis

# Command to run tests, e.g. python setup.py test
script:
  - tox